### ISSUE TITLE
"400 Client Error: Bad Request" with gru-up

### ISSUE THREAD

**Issue by Vayel** [departement-loire-atlantique/publik#2]
Hi!

I get an error when I run the containers:

```bash
$ gru-up
Creating network "publik_default" with the default driver
Creating volume "publik_dbdata" with default driver
Creating volume "publik_hobodata" with default driver
Creating volume "publik_wcsdata" with default driver
Creating volume "publik_authentic2data" with default driver
Creating volume "publik_combodata" with default driver
Creating volume "publik_fargodata" with default driver
Creating volume "publik_passerelledata" with default driver
Creating db          ... done
Creating rabbitmq    ... done
Creating mailcatcher ... done
Creating base        ...
Creating pgadmin     ... done
Creating wcs         ...
Creating fargo       ...
Creating passerelle  ...
Creating hobo        ...
Creating base        ... done
Creating combo       ...
ERROR: for hobo  a bytes-like object is required, not 'str'
ERROR: for wcs  a bytes-like object is required, not 'str'
ERROR: for authentic  a bytes-like object is required, not 'str'
ERROR: for passerelle  a bytes-like object is required, not 'str'
ERROR: for combo  a bytes-like object is required, not 'str'
ERROR: for fargo  a bytes-like object is required, not 'str'
ERROR: for hobo  a bytes-like object is required, not 'str'
ERROR: for wcs  a bytes-like object is required, not 'str'
ERROR: for authentic  a bytes-like object is required, not 'str'
ERROR: for passerelle  a bytes-like object is required, not 'str'
ERROR: for combo  a bytes-like object is required, not 'str'
ERROR: for fargo  a bytes-like object is required, not 'str'
Traceback (most recent call last):
File "site-packages/docker/api/client.py", line 261, in _raise_for_status
File "site-packages/requests/models.py", line 940, in raise_for_status
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.22/containers/8ba28645e2cbedb26fc4bab3ec1518a0762931a6a3b1340ae2dac230a4b3ece2/start
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "compose/service.py", line 625, in start_container
File "compose/container.py", line 241, in start
File "site-packages/docker/utils/decorators.py", line 19, in wrapped
File "site-packages/docker/api/container.py", line 1095, in start
File "site-packages/docker/api/client.py", line 263, in _raise_for_status
File "site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 400 Client Error: Bad Request ("b'OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \\"rootfs_linux.go:58: mounting \\\\\\"/home/publik/publik/data/hosts\\\\\\" to rootfs \\\\\\"/var/lib/docker/overlay2/be6bf474f74a5ec1c95d6c74708839b40cab5bd04a5e4f134e68e786dd1cfd67/merged\\\\\\" at \\\\\\"/var/lib/docker/overlay2/be6bf474f74a5ec1c95d6c74708839b40cab5bd04a5e4f134e68e786dd1cfd67/merged/etc/hosts\\\\\\" caused \\\\\\"not a directory\\\\\\"\\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type'")
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "bin/docker-compose", line 6, in <module>
File "compose/cli/main.py", line 72, in main
File "compose/cli/main.py", line 128, in perform_command
File "compose/cli/main.py", line 1107, in up
File "compose/cli/main.py", line 1103, in up
File "compose/project.py", line 570, in up
File "compose/parallel.py", line 112, in parallel_execute
File "compose/parallel.py", line 210, in producer
File "compose/project.py", line 556, in do
File "compose/service.py", line 546, in execute_convergence_plan
File "compose/service.py", line 467, in _execute_convergence_create
File "compose/parallel.py", line 112, in parallel_execute
File "compose/parallel.py", line 210, in producer
File "compose/service.py", line 465, in <lambda>
File "compose/service.py", line 457, in create_and_start
File "compose/service.py", line 627, in start_container
TypeError: a bytes-like object is required, not 'str'
[8179] Failed to execute script docker-compose
```

Here is the environment I use:

```bash
$ uname -a
Linux reverseip 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u1 (2019-09-20) x86_64 GNU/Linux
$ docker-compose version
docker-compose version 1.25.0, build 0a186604
docker-py version: 4.1.0
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

Thanks!

**Comment by Vayel** [comment]
It seems related to the fact that `data/hosts/` is a folder instead of a file.
